# Generated by Django 5.0.2 on 2024-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortTcpScanner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("idScanner", models.IntegerField()),
                ("port", models.TextField()),
                ("protocol", models.TextField()),
                ("service", models.TextField()),
                ("state", models.TextField()),
            ],
        ),
    ]
