# Generated by Django 5.0.2 on 2024-02-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DnsResolverIpv4",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("host", models.TextField()),
                ("ipv4", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DnsResolverIpv6",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("host", models.TextField()),
                ("ipv6", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MailServer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("host", models.TextField()),
                ("server", models.TextField()),
                ("priority", models.IntegerField()),
            ],
        ),
    ]
