# Generated by Django 5.0.2 on 2024-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0003_portscanner_porttcpscannerline_delete_porttcpscanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="portscanner",
            name="idUser",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
