# Generated by Django 5.0.2 on 2024-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0004_portscanner_iduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="porttcpscannerline",
            name="version",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
