# Generated by Django 5.0.2 on 2024-03-08 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0007_alter_porttcpscannerline_scanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="porttcpscannerline",
            name="scanner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nmap.portscanner"
            ),
        ),
    ]
