# Generated by Django 5.0.2 on 2024-03-08 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0008_alter_porttcpscannerline_scanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="porttcpscannerline",
            name="scanner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scannerline",
                to="nmap.portscanner",
            ),
        ),
    ]
