# Generated by Django 5.0.2 on 2024-03-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0010_alter_porttcpscannerline_scanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="portscanner",
            name="network_distance",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portscanner",
            name="uptime",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
