# Generated by Django 5.0.2 on 2024-03-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0011_portscanner_network_distance_portscanner_uptime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portscanner",
            old_name="network_distance",
            new_name="network_distance_in_hops",
        ),
        migrations.RenameField(
            model_name="portscanner",
            old_name="uptime",
            new_name="uptime_in_days",
        ),
    ]
