# Generated by Django 5.0.2 on 2024-03-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "nmap",
            "0012_rename_network_distance_portscanner_network_distance_in_hops_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PortTcpScannerLine",
            new_name="PortScannerLine",
        ),
    ]
