# Generated by Django 5.0.2 on 2024-03-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0013_rename_porttcpscannerline_portscannerline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portscanner",
            name="network_distance_in_hops",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="uptime_in_days",
            field=models.IntegerField(),
        ),
    ]
