# Generated by Django 5.0.2 on 2024-03-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0014_alter_portscanner_network_distance_in_hops_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portscannerline",
            old_name="version",
            new_name="service_version",
        ),
    ]
