# Generated by Django 5.0.2 on 2024-03-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0015_rename_version_portscannerline_service_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portscannerline",
            old_name="scanner",
            new_name="port_scanner",
        ),
    ]
