# Generated by Django 5.0.2 on 2024-03-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0017_rename_port_scanner_portscannerline_port_scannerr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portscannerline",
            old_name="port_scannerr",
            new_name="port_scanner",
        ),
    ]
