# Generated by Django 5.0.2 on 2024-03-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0018_rename_port_scannerr_portscannerline_port_scanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortScannerReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="portscanner",
            name="port_scanner_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="nmap.portscannerreport",
            ),
        ),
    ]
