# Generated by Django 5.0.2 on 2024-03-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0020_alter_portscanner_port_scanner_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portscanner",
            name="port_scanner_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aux",
                to="nmap.portscannerreport",
            ),
        ),
    ]
