# Generated by Django 5.0.2 on 2024-03-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0021_alter_portscanner_port_scanner_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portscanner",
            name="port_scanner_report",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="nmap.portscannerreport",
            ),
        ),
    ]
