# Generated by Django 5.0.2 on 2024-03-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0022_alter_portscanner_port_scanner_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portscanner",
            name="port_scanner_report",
        ),
        migrations.RemoveField(
            model_name="portscannerreport",
            name="id",
        ),
        migrations.AddField(
            model_name="portscannerreport",
            name="idPortScanner",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="nmap.portscanner",
            ),
            preserve_default=False,
        ),
    ]
