# Generated by Django 5.0.2 on 2024-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0023_remove_portscanner_port_scanner_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portscanner",
            name="network_distance_in_hops",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="uptime_in_days",
            field=models.IntegerField(null=True),
        ),
    ]
