# Generated by Django 5.0.2 on 2024-03-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0024_alter_portscanner_network_distance_in_hops_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portscannerreport",
            name="idPortScanner",
        ),
        migrations.AddField(
            model_name="portscanner",
            name="port_scanner_report",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="nmap.portscannerreport",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portscannerreport",
            name="id",
            field=models.AutoField(default=119, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="network_distance_in_hops",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="uptime_in_days",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
