# Generated by Django 5.0.2 on 2024-03-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0025_remove_portscannerreport_idportscanner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portscanner",
            name="port_scanner_report",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="nmap.portscannerreport",
            ),
        ),
    ]
