# Generated by Django 5.0.2 on 2024-03-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0026_alter_portscanner_port_scanner_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portscanner",
            name="port_scanner_report",
        ),
        migrations.AddField(
            model_name="portscannerreport",
            name="port_scanner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="nmap.portscanner",
            ),
        ),
    ]
