# Generated by Django 5.0.2 on 2024-03-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0027_remove_portscanner_port_scanner_report_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portscannerreport",
            name="id",
        ),
        migrations.AlterField(
            model_name="portscannerreport",
            name="port_scanner",
            field=models.OneToOneField(
                default=119,
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="nmap.portscanner",
            ),
            preserve_default=False,
        ),
    ]
