# Generated by Django 5.0.2 on 2024-03-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmap", "0028_remove_portscannerreport_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portscannerreport",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portscannerreport",
            name="port_scanner",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="nmap.portscanner",
            ),
        ),
    ]
